services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    container_name: desafio-app1
    environment:
      - FLASK_ENV=production
      - PORT=8000
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    container_name: desafio-app2
    environment:
      - FLASK_ENV=production
      - PORT=8000
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: desafio-proxy
    ports:
      - "80:80"
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3

networks:
  app-network:
    driver: bridge
    name: desafio-network